blank_issues_enabled: true
contact_links:
  - name: Feature request (and other issues)
    url: https://github.com/owid/covid-19-data/discussions/categories/ideas
    about: Feature requests may be raised as an "Ideas" discussion.
