blank_issues_enabled: true
contact_links:
  - name: Feature request
    url: https://github.com/owid/covid-19-data/discussions/categories/ideas
    about: Are we missing something? Feature requests may be raised as an "Ideas" discussion.
  - name: Our dev documentation 📚
    url: https://covid-docs.ourworldindata.org/
    about: Refer to our developer documentation to know more about how we operate this project. 
